// Vercel serverless function: /api/chat
// Works as a Vercel API route AND can be imported by a local Express server
// Supports tool_use agentic loop for Cowork mode (web search via Brave)
// Supports Agent Skills (PPTX, XLSX, DOCX, PDF) via code execution container

async function executeBraveSearch(query) {
  const braveKey = process.env.BRAVE_SEARCH_API_KEY;
  if (!braveKey) {
    return { error: "BRAVE_SEARCH_API_KEY not configured on server" };
  }
  try {
    const url = `https://api.search.brave.com/res/v1/web/search?q=${encodeURIComponent(query)}&count=5`;
    const response = await fetch(url, {
      headers: { "X-Subscription-Token": braveKey },
    });
    if (!response.ok) {
      return { error: `Brave Search returned ${response.status}` };
    }
    const data = await response.json();
    return {
      results: (data.web?.results || []).map((r) => ({
        title: r.title,
        url: r.url,
        description: r.description,
      })),
    };
  } catch (err) {
    return { error: `Brave Search failed: ${err.message}` };
  }
}

async function executeToolCall(name, input) {
  if (name === "web_search") {
    return await executeBraveSearch(input.query);
  }
  return { error: `Unknown tool: ${name}` };
}

// Extract file references from response content blocks (code execution results)
function extractFiles(content) {
  const files = [];
  for (const block of (content || [])) {
    // Direct file_id on a block (e.g. code_execution_tool_result)
    if (block.file_id) {
      files.push({ file_id: block.file_id, filename: block.filename || null });
    }
    // Nested content array (bash_code_execution_tool_result, server_tool_result, etc.)
    const inner = Array.isArray(block.content) ? block.content : [];
    for (const item of inner) {
      if (item.file_id) {
        files.push({ file_id: item.file_id, filename: item.filename || null });
      }
      // Deeper nesting — some results have content.content
      const deeper = Array.isArray(item.content) ? item.content : [];
      for (const deep of deeper) {
        if (deep.file_id) {
          files.push({ file_id: deep.file_id, filename: deep.filename || null });
        }
      }
    }
  }
  return files;
}

export default async function handler(req, res) {
  // CORS headers for local dev
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: "ANTHROPIC_API_KEY not configured" });
  }

  try {
    const { system, messages, model, max_tokens, tools, tool_choice, container } = req.body;

    const MAX_ITERATIONS = 10;
    let currentMessages = [...(messages || [])];
    let toolCallsLog = [];
    let allToolResults = []; // raw results to return for conversation persistence
    let allFiles = []; // files generated by code execution

    // Build headers — add beta headers when skills/container are present
    const headers = {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    };
    if (container) {
      headers["anthropic-beta"] = "code-execution-2025-08-25,skills-2025-10-02,files-api-2025-04-14";
    }

    // Mutable container config — updated with container_id from responses
    let containerConfig = container ? { ...container } : null;

    for (let i = 0; i < MAX_ITERATIONS; i++) {
      const body = {
        model: model || "claude-sonnet-4-5-20250929",
        max_tokens: max_tokens || 1000,
        system: system || "",
        messages: currentMessages,
      };
      if (tools && tools.length > 0) body.tools = tools;
      if (tool_choice) body.tool_choice = tool_choice;
      if (containerConfig) body.container = containerConfig;

      const response = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers,
        body: JSON.stringify(body),
      });

      const data = await response.json();

      if (!response.ok) {
        return res.status(response.status).json(data);
      }

      // Capture container_id for reuse in subsequent iterations
      if (data.container_id && containerConfig) {
        containerConfig.id = data.container_id;
      }

      // Collect any files from this response
      const iterFiles = extractFiles(data.content);
      allFiles.push(...iterFiles);
      // Debug: log content block types for diagnosing file extraction
      if (data.content) {
        const blockTypes = data.content.map(b => b.type);
        console.log("[chat] iteration", i, "stop_reason:", data.stop_reason, "block types:", blockTypes.join(", "), "files found:", iterFiles.length);
      }

      // Handle pause_turn — code execution still running, continue the conversation
      if (data.stop_reason === "pause_turn") {
        currentMessages.push({ role: "assistant", content: data.content });
        currentMessages.push({ role: "user", content: [{ type: "text", text: "Please continue." }] });
        continue;
      }

      // If Claude didn't request tool use, return the final response
      if (data.stop_reason !== "tool_use") {
        if (toolCallsLog.length > 0) {
          data._toolCalls = toolCallsLog;
          // Build a compact summary of all search results for conversation persistence
          const lines = [];
          for (const tr of allToolResults) {
            lines.push(`Search: "${tr.query}"`);
            for (const r of tr.results) {
              lines.push(`- ${r.title}: ${r.url}`);
              if (r.description) lines.push(`  ${r.description}`);
            }
          }
          if (lines.length > 0) data._searchContext = lines.join("\n");
        }
        if (allFiles.length > 0) data._files = allFiles;
        if (containerConfig?.id) data._containerId = containerConfig.id;
        return res.status(200).json(data);
      }

      // Claude wants to use our custom tools — execute them
      // Only dispatch type: "tool_use" (our tools), NOT "server_tool_use" (Anthropic-managed)
      const toolUseBlocks = data.content.filter((b) => b.type === "tool_use");
      const toolResultBlocks = [];

      for (const toolUse of toolUseBlocks) {
        const result = await executeToolCall(toolUse.name, toolUse.input);
        toolCallsLog.push({
          tool: toolUse.name,
          input: toolUse.input,
          resultSummary: result.error
            ? `Error: ${result.error}`
            : `${(result.results || []).length} results`,
        });
        // Store raw results for conversation persistence
        if (result.results) {
          allToolResults.push({ query: toolUse.input.query, results: result.results });
        }
        toolResultBlocks.push({
          type: "tool_result",
          tool_use_id: toolUse.id,
          content: JSON.stringify(result),
        });
      }

      // Append assistant response + tool results, then loop
      currentMessages.push({ role: "assistant", content: data.content });
      currentMessages.push({ role: "user", content: toolResultBlocks });
    }

    // Hit max iterations — return what we have
    return res.status(200).json({
      content: [{ type: "text", text: "I performed several operations but reached the iteration limit. Please try a more specific question." }],
      _toolCalls: toolCallsLog,
      _files: allFiles.length > 0 ? allFiles : undefined,
      _containerId: containerConfig?.id || undefined,
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
